server:
  port: 3333
  host: '127.0.0.1'

db:
  name: './ankor_sqlite.db'

providers:
  google:
    api_host: 'www.googleapis.com'
    api_path: '/urlshortener/v1/url'
    api_key: 'AIzaSyA9BoYSHYHTLmjIQzu-0MiAWL_fvPr5tzs'
